### ISSUE TITLE
Full View is not Rendered

### ISSUE THREAD

**Issue by dakshitagrawal** [sdsmdg/trianglify#23]
When the cell size of the grid is very large, there is space left on the right.  The problem could be in the bleed values.

**Comment by suyashmahar** [comment]
@dakshitagrawal97 I believe 2.2 section of Documentation explains this [2.2 Details of Bleed and Grid dimensions](https://github.com/sdsmdg/trianglify#22-details-of-bleed-and-grid-dimensions)

**Comment by dakshitagrawal** [comment]
@suyashmahar the 2.2 section states that the total area visible is (gridHeight + bleedY)*(gridWidth + bleedX). The app has the gridHeight and width set to match parent. There is a padding of 16dp and margin of 8dp.  BleedX and BleedY have been set to 50dp. Hence, there should not be any space left.

**Comment by suyashmahar** [comment]
@dakshitagrawal97 
> Bleed: Bleed defines the dimensions of extra size that TrianglifyView view generate so that triangles on the edge doesn't appear to be chopped off. **In most of the cases min{bleedX, bleedY} > cellSize would ensure that the view is completely filled.**

I was referring to the emphasized part, It says when cell size is large such that above inequality doesn't holds true, view will show white spaces. However we can make sure that above inequality holds true in our demo app.

**Comment by suyashmahar** [comment]
@dakshitagrawal97 I think the issue has been addressed.

**Comment by dakshitagrawal** [comment]
@suyashmahar Yes, I overlooked that part. We should add the inequality checker on our part though.

**Comment by suyashmahar** [comment]
@dakshitagrawal97 I don't think that would be a good idea we should not control every aspect of trianglify behavior. User should be in control of every thing, though we can make it optional.

**Comment by dakshitagrawal** [comment]
@suyashmahar The user would want that the view is filled completely into the space that is designated to the view. We can give a toast message to notify the user of the problem so that he can rectify it on his own. For the app, we should take care of it from our side.

**Comment by suyashmahar** [comment]
@dakshitagrawal97 Showing toast notification or messages from library is a bad idea, however handling in our app seems right.
