### ISSUE TITLE
not filling full space in Landscape mode

### ISSUE THREAD

**Issue by arihant-001** [sdsmdg/trianglify#37]
![screenshot_20170524_002](https://cloud.githubusercontent.com/assets/23583851/26402715/086bbef0-40a9-11e7-8a05-ae377666ab7b.png)
![screenshot_20170524_003](https://cloud.githubusercontent.com/assets/23583851/26402714/0868b49e-40a9-11e7-8ed6-a726598b196f.png)

**Comment by suyashmahar** [comment]
This is same as #23, closing
